In [4]:
import pandas as pd

In [1]:
 data = {
    'key': ['A', 'B', 'C', 'D', 'E', 'A', 'B', '6', 'D', 'E', 'A', 'B', '9', 'D', 'E'],
    'value': ['tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag1', 'tag2', 'tag3', 'tag4', 'tag5'],

}

In [5]:
df = pd.DataFGrame(data)

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [ ]:
print(df["key"])
print(df["value"] == "tag")